from lista_nao_ordenada import *
minha_lista =ListaNaoOrdenada()
print(minha_lista)
minha_lista.add(5)
print(minha_lista)
minha_lista.add(50)
minha_lista.add(1)
minha_lista.add(3)
print(minha_lista)
print(minha_lista.size())
print(minha_lista.search(3))
print(minha_lista.search(1))
print(minha_lista.search(5))
print(minha_lista.search(51))
minha_lista.remove(31)
print(minha_lista)
minha_lista.remove(3)
print(minha_lista)
minha_lista.remove(50)
print(minha_lista)
minha_lista.remove(5)
print(minha_lista)
minha_lista.remove(1)
print(minha_lista)